apiVersion: v2
name: test-chart
description: A Helm chart for kyverno
version: 0.0.1

dependencies:
  - name: kyverno
    version: 3.0.9
    repository: "https://repo.bab.net.au/artifactory/helm"
  - name: echo-server
    version: 0.5.0
    repository: "https://ealenn.github.io/charts"